version: '3.8'
services:
  astro:
    image: node:lts
    container_name: astro-dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4321:4321"
    command: sh -c "npm install && npm run dev"

    env_file:
      - .env

  astro-build:
    image: node:lts
    container_name: astro-build
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run build"
    env_file:
      - .env
